CREATE TABLE IF NOT EXISTS "migrations" ("id" integer primary key autoincrement not null, "migration" varchar not null, "batch" integer not null);
CREATE TABLE IF NOT EXISTS "users" ("id" integer primary key autoincrement not null, "name" varchar not null, "email" varchar not null, "email_verified_at" datetime, "password" varchar not null, "active" tinyint(1) not null default '1', "remember_token" varchar, "created_at" datetime, "updated_at" datetime);
CREATE UNIQUE INDEX "users_email_unique" on "users" ("email");
CREATE TABLE IF NOT EXISTS "password_reset_tokens" ("email" varchar not null, "token" varchar not null, "created_at" datetime, primary key ("email"));
CREATE TABLE IF NOT EXISTS "failed_jobs" ("id" integer primary key autoincrement not null, "uuid" varchar not null, "connection" text not null, "queue" text not null, "payload" text not null, "exception" text not null, "failed_at" datetime not null default CURRENT_TIMESTAMP);
CREATE UNIQUE INDEX "failed_jobs_uuid_unique" on "failed_jobs" ("uuid");
CREATE TABLE IF NOT EXISTS "personal_access_tokens" ("id" integer primary key autoincrement not null, "tokenable_type" varchar not null, "tokenable_id" integer not null, "name" varchar not null, "token" varchar not null, "abilities" text, "last_used_at" datetime, "expires_at" datetime, "created_at" datetime, "updated_at" datetime);
CREATE INDEX "personal_access_tokens_tokenable_type_tokenable_id_index" on "personal_access_tokens" ("tokenable_type", "tokenable_id");
CREATE UNIQUE INDEX "personal_access_tokens_token_unique" on "personal_access_tokens" ("token");
CREATE TABLE IF NOT EXISTS "permissions" ("id" integer primary key autoincrement not null, "name" varchar not null, "guard_name" varchar not null, "created_at" datetime, "updated_at" datetime);
CREATE UNIQUE INDEX "permissions_name_guard_name_unique" on "permissions" ("name", "guard_name");
CREATE TABLE IF NOT EXISTS "roles" ("id" integer primary key autoincrement not null, "name" varchar not null, "guard_name" varchar not null, "created_at" datetime, "updated_at" datetime);
CREATE UNIQUE INDEX "roles_name_guard_name_unique" on "roles" ("name", "guard_name");
CREATE TABLE IF NOT EXISTS "model_has_permissions" ("permission_id" integer not null, "model_type" varchar not null, "model_id" integer not null, foreign key("permission_id") references "permissions"("id") on delete cascade, primary key ("permission_id", "model_id", "model_type"));
CREATE INDEX "model_has_permissions_model_id_model_type_index" on "model_has_permissions" ("model_id", "model_type");
CREATE TABLE IF NOT EXISTS "model_has_roles" ("role_id" integer not null, "model_type" varchar not null, "model_id" integer not null, foreign key("role_id") references "roles"("id") on delete cascade, primary key ("role_id", "model_id", "model_type"));
CREATE INDEX "model_has_roles_model_id_model_type_index" on "model_has_roles" ("model_id", "model_type");
CREATE TABLE IF NOT EXISTS "role_has_permissions" ("permission_id" integer not null, "role_id" integer not null, foreign key("permission_id") references "permissions"("id") on delete cascade, foreign key("role_id") references "roles"("id") on delete cascade, primary key ("permission_id", "role_id"));
CREATE TABLE IF NOT EXISTS "categorias" ("id" integer primary key autoincrement not null, "nombre" varchar not null, "descripcion" varchar, "activo" tinyint(1) not null default '1', "created_at" datetime, "updated_at" datetime, "deleted_at" datetime);
CREATE INDEX "categorias_activo_nombre_index" on "categorias" ("activo", "nombre");
CREATE TABLE IF NOT EXISTS "laboratorios" ("id" integer primary key autoincrement not null, "nombre" varchar not null, "codigo" varchar, "contacto" varchar, "telefono" varchar, "email" varchar, "pais_origen" varchar, "activo" tinyint(1) not null default '1', "created_at" datetime, "updated_at" datetime);
CREATE INDEX "laboratorios_nombre_index" on "laboratorios" ("nombre");
CREATE INDEX "laboratorios_activo_index" on "laboratorios" ("activo");
CREATE UNIQUE INDEX "laboratorios_nombre_unique" on "laboratorios" ("nombre");
CREATE UNIQUE INDEX "laboratorios_codigo_unique" on "laboratorios" ("codigo");
CREATE TABLE IF NOT EXISTS "proveedores" ("id" integer primary key autoincrement not null, "nombre" varchar not null, "ruc" varchar not null, "contacto" varchar, "telefono" varchar, "email" varchar, "direccion" text, "activo" tinyint(1) not null default '1', "created_at" datetime, "updated_at" datetime, "deleted_at" datetime);
CREATE INDEX "proveedores_activo_index" on "proveedores" ("activo");
CREATE UNIQUE INDEX "proveedores_ruc_unique" on "proveedores" ("ruc");
CREATE TABLE IF NOT EXISTS "clientes" ("id" integer primary key autoincrement not null, "nombre" varchar not null, "documento" varchar, "telefono" varchar, "email" varchar, "direccion" text, "activo" tinyint(1) not null default '1', "created_at" datetime, "updated_at" datetime, "deleted_at" datetime);
CREATE INDEX "clientes_documento_index" on "clientes" ("documento");
CREATE INDEX "clientes_activo_index" on "clientes" ("activo");
CREATE TABLE IF NOT EXISTS "productos" ("id" integer primary key autoincrement not null, "codigo_barra" varchar, "nombre" varchar not null, "principio_activo" varchar, "concentracion" varchar, "forma_farmaceutica" varchar, "descripcion" text, "imagen" varchar, "categoria_id" integer not null, "laboratorio_id" integer, "registro_sanitario" varchar, "tipo_control" varchar check ("tipo_control" in ('venta_libre', 'controlado')) not null default 'venta_libre', "nivel_controlado" integer not null default '1', "precio_compra" numeric not null default '0', "precio_venta" numeric not null, "stock_minimo" integer not null default '0', "ubicacion" varchar, "requiere_receta" tinyint(1) not null default '0', "activo" tinyint(1) not null default '1', "created_at" datetime, "updated_at" datetime, "deleted_at" datetime, foreign key("categoria_id") references "categorias"("id") on delete restrict, foreign key("laboratorio_id") references "laboratorios"("id") on delete set null);
CREATE INDEX "productos_categoria_id_activo_index" on "productos" ("categoria_id", "activo");
CREATE INDEX "productos_laboratorio_id_activo_index" on "productos" ("laboratorio_id", "activo");
CREATE INDEX "productos_nombre_index" on "productos" ("nombre");
CREATE INDEX "productos_principio_activo_index" on "productos" ("principio_activo");
CREATE INDEX "productos_tipo_control_index" on "productos" ("tipo_control");
CREATE UNIQUE INDEX "productos_codigo_barra_unique" on "productos" ("codigo_barra");
CREATE TABLE IF NOT EXISTS "presentaciones_producto" ("id" integer primary key autoincrement not null, "producto_id" integer not null, "nombre" varchar not null, "descripcion" varchar, "unidades_por_presentacion" integer not null default '1', "precio_compra" numeric, "precio_venta" numeric, "codigo_barras" varchar, "es_unidad_base" tinyint(1) not null default '0', "activo" tinyint(1) not null default '1', "orden" integer not null default '0', "created_at" datetime, "updated_at" datetime, foreign key("producto_id") references "productos"("id") on delete cascade);
CREATE INDEX "presentaciones_producto_producto_id_activo_index" on "presentaciones_producto" ("producto_id", "activo");
CREATE TABLE IF NOT EXISTS "recetas" ("id" integer primary key autoincrement not null, "cliente_id" integer, "paciente_nombre" varchar not null, "paciente_documento" varchar, "paciente_edad" integer, "medico_nombre" varchar not null, "medico_colegiatura" varchar not null, "medico_especialidad" varchar, "institucion_salud" varchar, "numero_receta" varchar not null, "fecha_emision" date not null, "fecha_vencimiento" date, "tipo_receta" varchar not null default 'general', "archivo_receta" varchar, "estado" varchar check ("estado" in ('pendiente', 'dispensada_parcial', 'dispensada_total', 'anulada')) not null default 'pendiente', "observaciones" text, "created_at" datetime, "updated_at" datetime, foreign key("cliente_id") references "clientes"("id") on delete set null);
CREATE INDEX "recetas_cliente_id_index" on "recetas" ("cliente_id");
CREATE INDEX "recetas_numero_receta_index" on "recetas" ("numero_receta");
CREATE INDEX "recetas_fecha_emision_index" on "recetas" ("fecha_emision");
CREATE INDEX "recetas_estado_index" on "recetas" ("estado");
CREATE UNIQUE INDEX "recetas_numero_receta_unique" on "recetas" ("numero_receta");
CREATE TABLE IF NOT EXISTS "receta_detalles" ("id" integer primary key autoincrement not null, "receta_id" integer not null, "producto_id" integer not null, "cantidad_recetada" integer not null, "cantidad_dispensada" integer not null default '0', "posologia" varchar, "created_at" datetime, "updated_at" datetime, foreign key("receta_id") references "recetas"("id") on delete cascade, foreign key("producto_id") references "productos"("id") on delete restrict);
CREATE INDEX "receta_detalles_receta_id_producto_id_index" on "receta_detalles" ("receta_id", "producto_id");
CREATE TABLE IF NOT EXISTS "compras" ("id" integer primary key autoincrement not null, "proveedor_id" integer not null, "user_id" integer not null, "numero_comprobante" varchar, "subtotal" numeric not null default '0', "impuesto" numeric not null default '0', "total" numeric not null default '0', "estado" varchar check ("estado" in ('pendiente', 'recibida', 'anulada')) not null default 'recibida', "fecha" datetime not null, "fecha_anulacion" datetime, "anulado_por" integer, "motivo_anulacion" varchar, "compra_original_id" integer, "reemplazada_por" integer, "created_at" datetime, "updated_at" datetime, "condicion_pago" varchar check ("condicion_pago" in ('contado', 'credito')) not null default 'contado', "dias_credito" integer not null default '0', "fecha_vencimiento_pago" date, "saldo_pendiente" numeric not null default '0', "estado_pago" varchar check ("estado_pago" in ('pagado', 'pendiente', 'parcial', 'vencido')) not null default 'pagado', "orden_compra_id" integer, foreign key("proveedor_id") references "proveedores"("id") on delete restrict, foreign key("user_id") references "users"("id") on delete restrict, foreign key("anulado_por") references "users"("id") on delete set null, foreign key("compra_original_id") references "compras"("id") on delete set null, foreign key("reemplazada_por") references "compras"("id") on delete set null);
CREATE INDEX "compras_proveedor_id_fecha_index" on "compras" ("proveedor_id", "fecha");
CREATE INDEX "compras_estado_index" on "compras" ("estado");
CREATE TABLE IF NOT EXISTS "lotes" ("id" integer primary key autoincrement not null, "producto_id" integer not null, "compra_id" integer, "proveedor_id" integer, "numero_lote" varchar not null, "fecha_vencimiento" date not null, "stock_inicial" integer not null, "stock_actual" integer not null, "precio_compra" numeric not null, "activo" tinyint(1) not null default '1', "created_at" datetime, "updated_at" datetime, foreign key("producto_id") references "productos"("id") on delete restrict, foreign key("compra_id") references "compras"("id") on delete set null, foreign key("proveedor_id") references "proveedores"("id") on delete set null);
CREATE INDEX "lotes_producto_id_activo_fecha_vencimiento_index" on "lotes" ("producto_id", "activo", "fecha_vencimiento");
CREATE INDEX "lotes_producto_id_stock_actual_index" on "lotes" ("producto_id", "stock_actual");
CREATE INDEX "lotes_numero_lote_index" on "lotes" ("numero_lote");
CREATE TABLE IF NOT EXISTS "detalle_compra" ("id" integer primary key autoincrement not null, "compra_id" integer not null, "producto_id" integer not null, "lote_id" integer not null, "presentacion_id" integer, "tipo_presentacion" varchar, "unidades_por_presentacion" integer not null default '1', "cantidad_presentaciones" integer not null default '1', "cantidad_unidades_base" integer not null, "precio_unitario" numeric not null, "subtotal" numeric not null, "created_at" datetime, "updated_at" datetime, "detalle_orden_compra_id" integer, foreign key("compra_id") references "compras"("id") on delete cascade, foreign key("producto_id") references "productos"("id") on delete restrict, foreign key("lote_id") references "lotes"("id") on delete restrict, foreign key("presentacion_id") references "presentaciones_producto"("id") on delete set null);
CREATE INDEX "detalle_compra_compra_id_producto_id_index" on "detalle_compra" ("compra_id", "producto_id");
CREATE INDEX "detalle_compra_lote_id_index" on "detalle_compra" ("lote_id");
CREATE TABLE IF NOT EXISTS "ventas" ("id" integer primary key autoincrement not null, "cliente_id" integer, "user_id" integer not null, "sesion_caja_id" integer, "tipo_comprobante" varchar check ("tipo_comprobante" in ('ticket', 'boleta', 'factura', 'credito_fiscal')) not null default 'ticket', "serie" varchar, "numero_comprobante" varchar, "idempotency_key" varchar, "subtotal" numeric not null default '0', "descuento" numeric not null default '0', "impuesto" numeric not null default '0', "total" numeric not null default '0', "monto_recibido" numeric, "cambio" numeric, "notas" text, "metodo_pago" varchar check ("metodo_pago" in ('efectivo', 'tarjeta', 'transferencia', 'mixto')) not null default 'efectivo', "estado" varchar check ("estado" in ('completada', 'anulada')) not null default 'completada', "fecha" datetime not null, "fecha_anulacion" datetime, "anulado_por" integer, "motivo_anulacion" varchar, "venta_original_id" integer, "reemplazada_por" integer, "created_at" datetime, "updated_at" datetime, "tipo_descuento" varchar not null default 'monto', "porcentaje_descuento" numeric not null default '0', "receta_modalidad" varchar not null default 'sin_receta', "receta_omision_motivo" varchar, "referencia_pago" varchar, "observaciones" text, foreign key("cliente_id") references "clientes"("id") on delete set null, foreign key("user_id") references "users"("id") on delete restrict, foreign key("sesion_caja_id") references "sesiones_caja"("id") on delete set null, foreign key("anulado_por") references "users"("id") on delete set null, foreign key("venta_original_id") references "ventas"("id") on delete set null, foreign key("reemplazada_por") references "ventas"("id") on delete set null);
CREATE INDEX "idx_ventas_fecha_estado" on "ventas" ("fecha", "estado");
CREATE INDEX "idx_ventas_user_fecha" on "ventas" ("user_id", "fecha");
CREATE INDEX "idx_ventas_estado_fecha" on "ventas" ("estado", "fecha");
CREATE INDEX "idx_ventas_cliente_fecha" on "ventas" ("cliente_id", "fecha");
CREATE INDEX "idx_ventas_sesion_estado" on "ventas" ("sesion_caja_id", "estado");
CREATE INDEX "idx_ventas_numero_comp" on "ventas" ("numero_comprobante");
CREATE INDEX "idx_ventas_metodo_pago" on "ventas" ("metodo_pago");
CREATE INDEX "idx_ventas_tipo_comp" on "ventas" ("tipo_comprobante");
CREATE INDEX "idx_ventas_anulado_por" on "ventas" ("anulado_por");
CREATE UNIQUE INDEX "ventas_idempotency_key_unique" on "ventas" ("idempotency_key");
CREATE TABLE IF NOT EXISTS "detalle_venta" ("id" integer primary key autoincrement not null, "venta_id" integer not null, "producto_id" integer not null, "lote_id" integer not null, "presentacion_id" integer, "receta_detalle_id" integer, "cantidad" integer not null, "unidades_por_presentacion" integer not null default '1', "cantidad_unidades_base" integer not null, "precio_unitario" numeric not null, "subtotal" numeric not null, "created_at" datetime, "updated_at" datetime, foreign key("venta_id") references "ventas"("id") on delete cascade, foreign key("producto_id") references "productos"("id") on delete restrict, foreign key("lote_id") references "lotes"("id") on delete restrict, foreign key("presentacion_id") references "presentaciones_producto"("id") on delete set null, foreign key("receta_detalle_id") references "receta_detalles"("id") on delete set null);
CREATE INDEX "detalle_venta_venta_id_producto_id_index" on "detalle_venta" ("venta_id", "producto_id");
CREATE INDEX "detalle_venta_lote_id_index" on "detalle_venta" ("lote_id");
CREATE INDEX "detalle_venta_receta_detalle_id_index" on "detalle_venta" ("receta_detalle_id");
CREATE TABLE IF NOT EXISTS "venta_receta" ("id" integer primary key autoincrement not null, "venta_id" integer not null, "receta_id" integer not null, "created_at" datetime, "updated_at" datetime, foreign key("venta_id") references "ventas"("id") on delete cascade, foreign key("receta_id") references "recetas"("id") on delete cascade);
CREATE UNIQUE INDEX "venta_receta_venta_id_receta_id_unique" on "venta_receta" ("venta_id", "receta_id");
CREATE TABLE IF NOT EXISTS "movimientos_inventario" ("id" integer primary key autoincrement not null, "producto_id" integer not null, "lote_id" integer not null, "user_id" integer not null, "tipo" varchar check ("tipo" in ('entrada', 'salida', 'ajuste')) not null, "subtipo" varchar check ("subtipo" in ('compra', 'venta', 'anulacion_venta', 'anulacion_compra', 'ajuste_manual', 'merma_vencimiento', 'merma_danio', 'vencimiento_automatico', 'modificacion_venta', 'modificacion_compra')) not null default 'ajuste_manual', "cantidad" integer not null, "stock_anterior" integer not null, "stock_posterior" integer not null, "costo_unitario" numeric not null default '0', "costo_total" numeric not null default '0', "origen" varchar, "origen_id" integer, "motivo" varchar, "fecha_movimiento" datetime not null, "created_at" datetime, "updated_at" datetime, foreign key("producto_id") references "productos"("id") on delete restrict, foreign key("lote_id") references "lotes"("id") on delete restrict, foreign key("user_id") references "users"("id") on delete restrict);
CREATE INDEX "movimientos_inventario_producto_id_fecha_movimiento_index" on "movimientos_inventario" ("producto_id", "fecha_movimiento");
CREATE INDEX "movimientos_inventario_lote_id_fecha_movimiento_index" on "movimientos_inventario" ("lote_id", "fecha_movimiento");
CREATE INDEX "movimientos_inventario_tipo_subtipo_index" on "movimientos_inventario" ("tipo", "subtipo");
CREATE INDEX "movimientos_inventario_origen_origen_id_index" on "movimientos_inventario" ("origen", "origen_id");
CREATE TABLE IF NOT EXISTS "login_logs" ("id" integer primary key autoincrement not null, "user_id" integer not null, "tipo" varchar check ("tipo" in ('login', 'logout')) not null, "ip" varchar, "user_agent" text, "created_at" datetime not null default CURRENT_TIMESTAMP, foreign key("user_id") references "users"("id") on delete cascade);
CREATE TABLE IF NOT EXISTS "configuraciones" ("id" integer primary key autoincrement not null, "clave" varchar not null, "valor" text, "tipo" varchar not null default 'string', "grupo" varchar not null default 'general', "descripcion" varchar, "created_at" datetime, "updated_at" datetime);
CREATE INDEX "configuraciones_grupo_index" on "configuraciones" ("grupo");
CREATE UNIQUE INDEX "configuraciones_clave_unique" on "configuraciones" ("clave");
CREATE TABLE IF NOT EXISTS "cajas" ("id" integer primary key autoincrement not null, "nombre" varchar not null, "codigo" varchar not null, "descripcion" varchar, "ubicacion" varchar, "activo" tinyint(1) not null default '1', "created_at" datetime, "updated_at" datetime);
CREATE INDEX "cajas_activo_index" on "cajas" ("activo");
CREATE UNIQUE INDEX "cajas_codigo_unique" on "cajas" ("codigo");
CREATE TABLE IF NOT EXISTS "sesiones_caja" ("id" integer primary key autoincrement not null, "caja_id" integer not null, "user_id" integer not null, "monto_inicial" numeric not null default '0', "fecha_apertura" datetime not null, "observaciones_apertura" text, "fecha_cierre" datetime, "cerrado_por" integer, "monto_final_efectivo" numeric, "monto_esperado_efectivo" numeric not null default '0', "diferencia_efectivo" numeric not null default '0', "total_ventas_efectivo" numeric not null default '0', "total_ventas_tarjeta" numeric not null default '0', "total_ventas_transferencia" numeric not null default '0', "total_ventas_otros" numeric not null default '0', "total_ventas" numeric not null default '0', "total_ingresos_manuales" numeric not null default '0', "total_egresos_manuales" numeric not null default '0', "estado" varchar check ("estado" in ('abierta', 'cerrada')) not null default 'abierta', "observaciones_cierre" text, "created_at" datetime, "updated_at" datetime, foreign key("caja_id") references "cajas"("id") on delete cascade, foreign key("user_id") references "users"("id") on delete cascade, foreign key("cerrado_por") references "users"("id") on delete set null);
CREATE INDEX "sesiones_caja_caja_id_estado_index" on "sesiones_caja" ("caja_id", "estado");
CREATE INDEX "sesiones_caja_user_id_estado_index" on "sesiones_caja" ("user_id", "estado");
CREATE INDEX "sesiones_caja_fecha_apertura_index" on "sesiones_caja" ("fecha_apertura");
CREATE TABLE IF NOT EXISTS "movimientos_caja" ("id" integer primary key autoincrement not null, "sesion_caja_id" integer not null, "user_id" integer not null, "tipo" varchar check ("tipo" in ('ingreso', 'egreso')) not null, "monto" numeric not null, "concepto" varchar not null, "comprobante_referencia" varchar, "created_at" datetime, "updated_at" datetime, foreign key("sesion_caja_id") references "sesiones_caja"("id") on delete cascade, foreign key("user_id") references "users"("id") on delete cascade);
CREATE INDEX "movimientos_caja_sesion_caja_id_tipo_index" on "movimientos_caja" ("sesion_caja_id", "tipo");
CREATE TABLE IF NOT EXISTS "audit_logs" ("id" integer primary key autoincrement not null, "user_id" integer, "modulo" varchar not null, "accion" varchar not null, "descripcion" varchar not null, "detalles" text, "ip" varchar, "user_agent" text, "created_at" datetime not null default CURRENT_TIMESTAMP, foreign key("user_id") references "users"("id") on delete set null);
CREATE INDEX "idx_audit_logs_created_at" on "audit_logs" ("created_at");
CREATE INDEX "idx_audit_logs_modulo_accion" on "audit_logs" ("modulo", "accion");
CREATE INDEX "idx_audit_logs_user_date" on "audit_logs" ("user_id", "created_at");
CREATE TABLE IF NOT EXISTS "promociones" ("id" integer primary key autoincrement not null, "nombre" varchar not null, "descripcion" text, "tipo" varchar check ("tipo" in ('porcentaje', 'monto_fijo', '2x1', '3x2')) not null default 'porcentaje', "valor" numeric not null default '0', "alcance" varchar check ("alcance" in ('producto', 'categoria', 'laboratorio', 'general')) not null default 'producto', "producto_id" integer, "categoria_id" integer, "laboratorio_id" integer, "fecha_inicio" datetime not null, "fecha_fin" datetime not null, "min_unidades" integer not null default '1', "stock_limite" integer, "stock_consumido" integer not null default '0', "activo" tinyint(1) not null default '1', "created_at" datetime, "updated_at" datetime, "deleted_at" datetime, foreign key("producto_id") references "productos"("id") on delete cascade, foreign key("categoria_id") references "categorias"("id") on delete cascade, foreign key("laboratorio_id") references "laboratorios"("id") on delete cascade);
CREATE INDEX "promociones_activo_fecha_inicio_fecha_fin_index" on "promociones" ("activo", "fecha_inicio", "fecha_fin");
CREATE INDEX "promociones_alcance_activo_index" on "promociones" ("alcance", "activo");
CREATE INDEX "promociones_producto_id_index" on "promociones" ("producto_id");
CREATE INDEX "promociones_categoria_id_index" on "promociones" ("categoria_id");
CREATE INDEX "promociones_laboratorio_id_index" on "promociones" ("laboratorio_id");
CREATE TABLE IF NOT EXISTS "login_security_logs" ("id" integer primary key autoincrement not null, "ip" varchar not null, "email" varchar, "user_agent" varchar, "evento" varchar check ("evento" in ('intento_fallido', 'bloqueado', 'desbloqueado', 'exitoso')) not null, "intentos_acumulados" integer not null default '0', "bloqueado_hasta" datetime, "created_at" datetime not null default CURRENT_TIMESTAMP);
CREATE INDEX "login_security_logs_ip_index" on "login_security_logs" ("ip");
CREATE INDEX "login_security_logs_email_index" on "login_security_logs" ("email");
CREATE TABLE IF NOT EXISTS "historial_precios" ("id" integer primary key autoincrement not null, "producto_id" integer not null, "proveedor_id" integer not null, "compra_id" integer, "presentacion_id" integer, "tipo_presentacion" varchar not null default 'Unidad Base', "unidades_por_presentacion" integer not null default '1', "precio_compra" numeric not null, "precio_unitario_base" numeric not null, "tipo" varchar not null default 'compra', "fecha" datetime not null, "observaciones" text, "created_at" datetime, "updated_at" datetime, foreign key("producto_id") references "productos"("id") on delete cascade, foreign key("proveedor_id") references "proveedores"("id") on delete cascade, foreign key("compra_id") references "compras"("id") on delete set null, foreign key("presentacion_id") references "presentaciones_producto"("id") on delete set null);
CREATE INDEX "historial_precios_producto_id_proveedor_id_index" on "historial_precios" ("producto_id", "proveedor_id");
CREATE INDEX "historial_precios_producto_id_fecha_index" on "historial_precios" ("producto_id", "fecha");
CREATE INDEX "historial_precios_proveedor_id_fecha_index" on "historial_precios" ("proveedor_id", "fecha");
CREATE INDEX "historial_precios_tipo_index" on "historial_precios" ("tipo");
CREATE TABLE IF NOT EXISTS "registros_venta_controlados" ("id" integer primary key autoincrement not null, "tipo_movimiento" varchar not null default 'VENTA', "venta_id" integer, "devolucion_id" integer, "compra_id" integer, "movimiento_inventario_id" integer, "producto_id" integer not null, "lote_id" integer, "nivel_controlado" integer not null default '1', "paciente_nombre" varchar, "paciente_cedula" varchar, "paciente_edad" integer, "medico_nombre" varchar, "medico_cedula" varchar, "medico_num_registro" varchar, "motivo_omision" text, "ruta_foto_receta" varchar, "diagnostico" varchar, "cantidad" numeric not null, "unidad" varchar not null default 'unidad', "user_id" integer not null, "created_at" datetime, "updated_at" datetime, foreign key("venta_id") references "ventas"("id") on delete set null, foreign key("devolucion_id") references "devoluciones_ventas"("id") on delete set null, foreign key("compra_id") references "compras"("id") on delete set null, foreign key("movimiento_inventario_id") references "movimientos_inventario"("id") on delete set null, foreign key("producto_id") references "productos"("id"), foreign key("lote_id") references "lotes"("id") on delete set null, foreign key("user_id") references "users"("id"));
CREATE INDEX "idx_rvc_tipo_fecha" on "registros_venta_controlados" ("tipo_movimiento", "created_at");
CREATE INDEX "idx_rvc_venta" on "registros_venta_controlados" ("venta_id");
CREATE INDEX "idx_rvc_devolucion" on "registros_venta_controlados" ("devolucion_id");
CREATE INDEX "idx_rvc_producto_fecha" on "registros_venta_controlados" ("producto_id", "created_at");
CREATE INDEX "idx_rvc_lote_fecha" on "registros_venta_controlados" ("lote_id", "created_at");
CREATE TABLE IF NOT EXISTS "devoluciones_ventas" ("id" integer primary key autoincrement not null, "venta_id" integer not null, "user_id" integer not null, "sesion_caja_id" integer, "numero_devolucion" varchar not null, "tipo" varchar check ("tipo" in ('parcial', 'total')) not null default 'parcial', "motivo" varchar not null, "observaciones" text, "monto_total" numeric not null default '0', "metodo_reembolso" varchar check ("metodo_reembolso" in ('efectivo', 'transferencia', 'tarjeta', 'saldo_favor', 'sin_reembolso')) not null default 'efectivo', "banco" varchar, "numero_transaccion" varchar, "estado" varchar check ("estado" in ('completada', 'anulada')) not null default 'completada', "fecha" datetime not null, "created_at" datetime, "updated_at" datetime, foreign key("venta_id") references "ventas"("id") on delete cascade, foreign key("user_id") references "users"("id") on delete restrict, foreign key("sesion_caja_id") references "sesiones_caja"("id") on delete set null);
CREATE INDEX "devoluciones_ventas_venta_id_fecha_index" on "devoluciones_ventas" ("venta_id", "fecha");
CREATE INDEX "devoluciones_ventas_numero_devolucion_index" on "devoluciones_ventas" ("numero_devolucion");
CREATE INDEX "devoluciones_ventas_estado_index" on "devoluciones_ventas" ("estado");
CREATE UNIQUE INDEX "devoluciones_ventas_numero_devolucion_unique" on "devoluciones_ventas" ("numero_devolucion");
CREATE TABLE IF NOT EXISTS "detalle_devoluciones_ventas" ("id" integer primary key autoincrement not null, "devolucion_venta_id" integer not null, "detalle_venta_id" integer not null, "producto_id" integer not null, "lote_id" integer not null, "cantidad" integer not null, "unidades_por_presentacion" integer not null default '1', "cantidad_unidades_base" integer not null, "precio_unitario" numeric not null, "subtotal" numeric not null, "reingresa_a_stock" tinyint(1) not null default '1', "estado_producto" varchar check ("estado_producto" in ('buen_estado', 'danado', 'vencido')) not null default 'buen_estado', "created_at" datetime, "updated_at" datetime, foreign key("devolucion_venta_id") references "devoluciones_ventas"("id") on delete cascade, foreign key("detalle_venta_id") references "detalle_venta"("id") on delete restrict, foreign key("producto_id") references "productos"("id") on delete restrict, foreign key("lote_id") references "lotes"("id") on delete restrict);
CREATE INDEX "det_dev_prod_idx" on "detalle_devoluciones_ventas" ("devolucion_venta_id", "producto_id");
CREATE INDEX "compras_condicion_pago_estado_pago_index" on "compras" ("condicion_pago", "estado_pago");
CREATE INDEX "compras_fecha_vencimiento_pago_index" on "compras" ("fecha_vencimiento_pago");
CREATE TABLE IF NOT EXISTS "pagos_cuentas_por_pagar" ("id" integer primary key autoincrement not null, "compra_id" integer not null, "user_id" integer not null, "sesion_caja_id" integer, "numero_pago" varchar not null, "monto" numeric not null, "metodo_pago" varchar check ("metodo_pago" in ('efectivo', 'transferencia', 'cheque', 'otro')) not null default 'efectivo', "banco" varchar, "numero_referencia" varchar, "fecha_pago" datetime not null, "observaciones" text, "created_at" datetime, "updated_at" datetime, foreign key("compra_id") references "compras"("id") on delete cascade, foreign key("user_id") references "users"("id") on delete restrict, foreign key("sesion_caja_id") references "sesiones_caja"("id") on delete set null);
CREATE INDEX "pagos_cuentas_por_pagar_compra_id_fecha_pago_index" on "pagos_cuentas_por_pagar" ("compra_id", "fecha_pago");
CREATE UNIQUE INDEX "pagos_cuentas_por_pagar_numero_pago_unique" on "pagos_cuentas_por_pagar" ("numero_pago");
CREATE TABLE IF NOT EXISTS "ordenes_compras" ("id" integer primary key autoincrement not null, "proveedor_id" integer not null, "user_id" integer not null, "numero_orden" varchar not null, "fecha_emision" date not null, "fecha_esperada_entrega" date, "estado" varchar check ("estado" in ('borrador', 'enviada', 'recibida_parcial', 'recibida_total', 'cancelada')) not null default 'borrador', "condicion_pago" varchar check ("condicion_pago" in ('contado', 'credito')) not null default 'contado', "dias_credito" integer not null default '0', "subtotal" numeric not null default '0', "impuesto" numeric not null default '0', "total" numeric not null default '0', "observaciones" text, "compra_id" integer, "created_at" datetime, "updated_at" datetime, "cerrada_con_faltante" tinyint(1) not null default '0', "faltante_unidades" integer not null default '0', "cerrada_por_id" integer, "fecha_cierre" datetime, "motivo_faltante" text, foreign key("proveedor_id") references "proveedores"("id") on delete restrict, foreign key("user_id") references "users"("id") on delete restrict, foreign key("compra_id") references "compras"("id") on delete set null);
CREATE INDEX "ordenes_compras_proveedor_id_fecha_emision_index" on "ordenes_compras" ("proveedor_id", "fecha_emision");
CREATE INDEX "ordenes_compras_estado_index" on "ordenes_compras" ("estado");
CREATE UNIQUE INDEX "ordenes_compras_numero_orden_unique" on "ordenes_compras" ("numero_orden");
CREATE TABLE IF NOT EXISTS "detalle_ordenes_compras" ("id" integer primary key autoincrement not null, "orden_compra_id" integer not null, "producto_id" integer not null, "cantidad_solicitada" integer not null, "cantidad_recibida" integer not null default '0', "precio_unitario_estimado" numeric not null default '0', "subtotal" numeric not null default '0', "created_at" datetime, "updated_at" datetime, foreign key("orden_compra_id") references "ordenes_compras"("id") on delete cascade, foreign key("producto_id") references "productos"("id") on delete restrict);
CREATE INDEX "det_oc_prod_idx" on "detalle_ordenes_compras" ("orden_compra_id", "producto_id");
CREATE TABLE IF NOT EXISTS "precios_venta" ("id" integer primary key autoincrement not null, "producto_id" integer not null, "presentacion_id" integer, "precio" numeric not null, "vigente_desde" datetime not null default CURRENT_TIMESTAMP, "vigente_hasta" datetime, "motivo" text, "user_id" integer, "created_at" datetime, "updated_at" datetime, foreign key("producto_id") references "productos"("id") on delete cascade, foreign key("presentacion_id") references "presentaciones_producto"("id") on delete cascade, foreign key("user_id") references "users"("id") on delete set null);
CREATE INDEX "idx_pv_prod_vigente" on "precios_venta" ("producto_id", "vigente_hasta");
CREATE INDEX "idx_pv_prod_pres_vigente" on "precios_venta" ("producto_id", "presentacion_id", "vigente_hasta");
CREATE INDEX "idx_pv_user" on "precios_venta" ("user_id");
CREATE INDEX "idx_pv_desde" on "precios_venta" ("vigente_desde");
CREATE TABLE IF NOT EXISTS "conteos_inventario" ("id" integer primary key autoincrement not null, "nombre" varchar not null, "estado" varchar check ("estado" in ('borrador', 'en_proceso', 'completado', 'cancelado')) not null default 'borrador', "notas" text, "usuario_id" integer not null, "aprobado_por_id" integer, "total_lotes" integer not null default '0', "lotes_contados" integer not null default '0', "diferencia_total_unidades" integer not null default '0', "iniciado_en" datetime, "completado_en" datetime, "created_at" datetime, "updated_at" datetime, "laboratorios_ids" text, "categorias_ids" text, "regimen_venta" varchar not null default 'todos', "alcance_resumen" text, "idempotency_key" varchar, foreign key("usuario_id") references "users"("id"), foreign key("aprobado_por_id") references "users"("id"));
CREATE TABLE IF NOT EXISTS "detalles_conteo" ("id" integer primary key autoincrement not null, "conteo_id" integer not null, "lote_id" integer not null, "producto_id" integer not null, "stock_sistema" integer not null, "stock_fisico" integer, "diferencia" integer not null default '0', "ajustado" tinyint(1) not null default '0', "created_at" datetime, "updated_at" datetime, foreign key("conteo_id") references "conteos_inventario"("id") on delete cascade, foreign key("lote_id") references "lotes"("id"), foreign key("producto_id") references "productos"("id"));
CREATE TABLE IF NOT EXISTS "devoluciones_compra" ("id" integer primary key autoincrement not null, "numero_devolucion" varchar not null, "proveedor_id" integer not null, "compra_id" integer, "usuario_id" integer not null, "estado" varchar check ("estado" in ('pendiente', 'enviada', 'confirmada', 'rechazada')) not null default 'pendiente', "motivo" text not null, "total_devolucion" numeric not null default '0', "fecha_envio" datetime, "created_at" datetime, "updated_at" datetime, foreign key("proveedor_id") references "proveedores"("id"), foreign key("compra_id") references "compras"("id") on delete set null, foreign key("usuario_id") references "users"("id"));
CREATE UNIQUE INDEX "devoluciones_compra_numero_devolucion_unique" on "devoluciones_compra" ("numero_devolucion");
CREATE TABLE IF NOT EXISTS "detalles_devolucion_compra" ("id" integer primary key autoincrement not null, "devolucion_compra_id" integer not null, "lote_id" integer not null, "producto_id" integer not null, "cantidad" integer not null, "precio_unitario" numeric not null default '0', "subtotal" numeric not null default '0', "motivo_detalle" varchar, "created_at" datetime, "updated_at" datetime, foreign key("devolucion_compra_id") references "devoluciones_compra"("id") on delete cascade, foreign key("lote_id") references "lotes"("id"), foreign key("producto_id") references "productos"("id"));
CREATE TABLE IF NOT EXISTS "cache" ("key" varchar not null, "value" text not null, "expiration" integer not null, primary key ("key"));
CREATE TABLE IF NOT EXISTS "cache_locks" ("key" varchar not null, "owner" varchar not null, "expiration" integer not null, primary key ("key"));
CREATE TABLE IF NOT EXISTS "sessions" ("id" varchar not null, "user_id" integer, "ip_address" varchar, "user_agent" text, "payload" text not null, "last_activity" integer not null, primary key ("id"));
CREATE INDEX "sessions_user_id_index" on "sessions" ("user_id");
CREATE INDEX "sessions_last_activity_index" on "sessions" ("last_activity");
CREATE TABLE IF NOT EXISTS "jobs" ("id" integer primary key autoincrement not null, "queue" varchar not null, "payload" text not null, "attempts" integer not null, "reserved_at" integer, "available_at" integer not null, "created_at" integer not null);
CREATE INDEX "jobs_queue_index" on "jobs" ("queue");
CREATE UNIQUE INDEX "conteos_inventario_idempotency_key_unique" on "conteos_inventario" ("idempotency_key");
CREATE INDEX "dev_comp_prov_fecha_idx" on "devoluciones_compra" ("proveedor_id", "created_at");
CREATE INDEX "dev_comp_estado_idx" on "devoluciones_compra" ("estado");
CREATE INDEX "dev_comp_compra_idx" on "devoluciones_compra" ("compra_id");
CREATE INDEX "det_devcomp_parent_prod_idx" on "detalles_devolucion_compra" ("devolucion_compra_id", "producto_id");
CREATE INDEX "det_devcomp_lote_idx" on "detalles_devolucion_compra" ("lote_id");
CREATE INDEX "conteo_estado_fecha_idx" on "conteos_inventario" ("estado", "created_at");
CREATE INDEX "conteo_usuario_idx" on "conteos_inventario" ("usuario_id");
CREATE INDEX "det_conteo_parent_idx" on "detalles_conteo" ("conteo_id", "producto_id");
CREATE INDEX "det_conteo_ajustado_idx" on "detalles_conteo" ("conteo_id", "ajustado");
CREATE INDEX "det_conteo_lote_idx" on "detalles_conteo" ("lote_id");
CREATE INDEX "pagos_cxp_metodo_fecha_idx" on "pagos_cuentas_por_pagar" ("metodo_pago", "fecha_pago");
CREATE INDEX "pv_prod_vigente_idx" on "precios_venta" ("producto_id", "vigente", "vigente_desde");
CREATE INDEX "pv_vigente_desde_idx" on "precios_venta" ("vigente_desde");
CREATE INDEX "oc_user_fecha_idx" on "ordenes_compras" ("user_id", "fecha_emision");
CREATE INDEX "oc_fecha_entrega_idx" on "ordenes_compras" ("fecha_esperada_entrega");
CREATE INDEX "prod_deleted_categoria_idx" on "productos" ("deleted_at", "categoria_id");
CREATE INDEX "prod_deleted_laboratorio_idx" on "productos" ("deleted_at", "laboratorio_id");
CREATE INDEX "prod_activo_nombre_idx" on "productos" ("activo", "nombre");
CREATE INDEX "compras_estadopago_venc_idx" on "compras" ("estado_pago", "fecha_vencimiento_pago");
CREATE INDEX "hp_prod_fecha_idx" on "historial_precios" ("producto_id", "created_at");
CREATE INDEX "mov_prod_lote_fecha_idx" on "movimientos_inventario" ("producto_id", "lote_id", "fecha_movimiento");
INSERT INTO migrations VALUES(1,'2014_10_12_000000_create_users_table',1);
INSERT INTO migrations VALUES(2,'2014_10_12_100000_create_password_reset_tokens_table',1);
INSERT INTO migrations VALUES(3,'2019_08_19_000000_create_failed_jobs_table',1);
INSERT INTO migrations VALUES(4,'2019_12_14_000001_create_personal_access_tokens_table',1);
INSERT INTO migrations VALUES(5,'2026_01_05_021618_create_permission_tables',1);
INSERT INTO migrations VALUES(6,'2026_01_09_032554_create_categorias_table',1);
INSERT INTO migrations VALUES(7,'2026_01_09_032555_create_laboratorios_table',1);
INSERT INTO migrations VALUES(8,'2026_01_09_032556_create_proveedores_table',1);
INSERT INTO migrations VALUES(9,'2026_01_09_032557_create_clientes_table',1);
INSERT INTO migrations VALUES(10,'2026_01_09_032559_create_productos_table',1);
INSERT INTO migrations VALUES(11,'2026_01_09_032600_create_presentaciones_producto_table',1);
INSERT INTO migrations VALUES(12,'2026_01_09_032601_create_recetas_table',1);
INSERT INTO migrations VALUES(13,'2026_01_09_032602_create_receta_detalles_table',1);
INSERT INTO migrations VALUES(14,'2026_01_09_032603_create_compras_table',1);
INSERT INTO migrations VALUES(15,'2026_01_09_032604_create_lotes_table',1);
INSERT INTO migrations VALUES(16,'2026_01_09_032606_create_detalle_compra_table',1);
INSERT INTO migrations VALUES(17,'2026_01_09_032607_create_ventas_table',1);
INSERT INTO migrations VALUES(18,'2026_01_09_032609_create_detalle_venta_table',1);
INSERT INTO migrations VALUES(19,'2026_01_09_032611_create_venta_receta_table',1);
INSERT INTO migrations VALUES(20,'2026_01_09_032612_create_movimientos_inventario_table',1);
INSERT INTO migrations VALUES(21,'2026_09_19_111528_create_login_logs_table',1);
INSERT INTO migrations VALUES(22,'2026_09_21_211000_create_configuraciones_table',1);
INSERT INTO migrations VALUES(23,'2026_09_21_211100_create_cajas_table',1);
INSERT INTO migrations VALUES(24,'2026_09_21_211200_create_sesiones_caja_table',1);
INSERT INTO migrations VALUES(25,'2026_09_21_211300_create_movimientos_caja_table',1);
INSERT INTO migrations VALUES(26,'2026_09_24_090000_create_audit_logs_table',1);
INSERT INTO migrations VALUES(27,'2026_09_24_142957_create_promociones_table',1);
INSERT INTO migrations VALUES(28,'2026_09_26_160000_create_login_security_logs_table',1);
INSERT INTO migrations VALUES(29,'2026_09_28_000001_create_historial_precios_table',1);
INSERT INTO migrations VALUES(30,'2026_09_28_224417_create_registros_venta_controlados_table',1);
INSERT INTO migrations VALUES(31,'2026_09_28_230001_create_devoluciones_ventas_tables',1);
INSERT INTO migrations VALUES(32,'2026_09_28_230002_add_credito_fields_to_compras_and_pagos_table',1);
INSERT INTO migrations VALUES(33,'2026_09_28_230003_create_ordenes_compras_tables',1);
INSERT INTO migrations VALUES(34,'2026_10_02_215839_create_precios_venta_table',1);
INSERT INTO migrations VALUES(35,'2026_10_02_230000_create_conteos_inventario_tables',1);
INSERT INTO migrations VALUES(36,'2026_10_02_240000_create_devoluciones_compra_table',1);
INSERT INTO migrations VALUES(37,'2026_10_03_012942_create_cache_table',2);
INSERT INTO migrations VALUES(38,'2026_10_03_012942_create_sessions_table',2);
INSERT INTO migrations VALUES(39,'2026_10_03_015720_create_jobs_table',2);
INSERT INTO migrations VALUES(40,'2026_10_03_154141_add_pos_fields_to_ventas_table',3);
INSERT INTO migrations VALUES(41,'2026_10_03_155910_add_partial_reception_fields_to_compras_and_ordenes',4);
INSERT INTO migrations VALUES(42,'2026_10_03_172829_add_scope_fields_to_conteos_inventario_table',5);
INSERT INTO migrations VALUES(43,'2026_10_03_231000_add_performance_indexes_to_new_modules',6);
